server:
  port: 8047
  servlet:
    context-path: /api-mq
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.125:3306/kaida?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    database: 0
    host: 192.168.3.125
    port: 6379
  jackson:
    time-zone: Asia/Shanghai
  # 消息队列服务器配置
  rabbitmq:
    host: 192.168.3.125
    port: 5672
    username: root
    password: 123456
    listener:
      direct:
        acknowledge-mode: MANUAL
      simple:
        acknowledge-mode: MANUAL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
url:
  client: http://127.0.0.1:8081
  kex: http://kex.free.idcfengye.com
  bl: http://127.0.0.1:8082
